// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SomeService.Data;

#nullable disable

namespace SomeService.Data.Migrations
{
    [DbContext(typeof(DellinDictionaryDbContext))]
    [Migration("20260309145255_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Office", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<int>("CityCode")
                        .HasColumnType("integer");

                    b.Property<string>("Code")
                        .HasColumnType("text");

                    b.Property<string>("CountryCode")
                        .HasColumnType("text");

                    b.Property<int?>("Type")
                        .HasColumnType("integer");

                    b.Property<string>("Uuid")
                        .HasColumnType("text");

                    b.Property<string>("WorkTime")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CityCode")
                        .HasDatabaseName("ix_offices_city_code");

                    b.HasIndex("Code")
                        .HasDatabaseName("ix_offices_code");

                    b.HasIndex("Uuid")
                        .HasDatabaseName("ix_offices_uuid");

                    b.ToTable("Offices");
                });

            modelBuilder.Entity("Office", b =>
                {
                    b.OwnsOne("SomeService.Data.Entities.Address", "Address", b1 =>
                        {
                            b1.Property<int>("OfficeId")
                                .HasColumnType("integer");

                            b1.Property<string>("City")
                                .HasColumnType("text");

                            b1.Property<string>("House")
                                .HasColumnType("text");

                            b1.Property<string>("PostalCode")
                                .HasColumnType("text");

                            b1.Property<string>("Region")
                                .HasColumnType("text");

                            b1.Property<string>("Street")
                                .HasColumnType("text");

                            b1.Property<string>("SubRegion")
                                .HasColumnType("text");

                            b1.HasKey("OfficeId");

                            b1.ToTable("Offices");

                            b1
                                .ToJson("address")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("OfficeId");
                        });

                    b.OwnsOne("SomeService.Data.Entities.Coordinates", "Coordinates", b1 =>
                        {
                            b1.Property<int>("OfficeId")
                                .HasColumnType("integer");

                            b1.Property<double>("CoordinateX")
                                .HasColumnType("double precision")
                                .HasAnnotation("Relational:JsonPropertyName", "сoordinateX");

                            b1.Property<double>("CoordinateY")
                                .HasColumnType("double precision")
                                .HasAnnotation("Relational:JsonPropertyName", "сoordinateY");

                            b1.HasKey("OfficeId");

                            b1.ToTable("Offices");

                            b1
                                .ToJson("coordinates")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("OfficeId");
                        });

                    b.OwnsMany("SomeService.Data.Entities.Phone", "Phones", b1 =>
                        {
                            b1.Property<int>("OfficeId")
                                .HasColumnType("integer");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            b1.Property<string>("Description")
                                .HasColumnType("text")
                                .HasAnnotation("Relational:JsonPropertyName", "description");

                            b1.Property<string>("Number")
                                .HasColumnType("text")
                                .HasAnnotation("Relational:JsonPropertyName", "number");

                            b1.HasKey("OfficeId", "__synthesizedOrdinal");

                            b1.ToTable("Offices");

                            b1
                                .ToJson("phones")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("OfficeId");
                        });

                    b.Navigation("Address")
                        .IsRequired();

                    b.Navigation("Coordinates")
                        .IsRequired();

                    b.Navigation("Phones");
                });
#pragma warning restore 612, 618
        }
    }
}
